version: '3.1'

services:
  # nodejs:
  #   image: bookstore-api
  #   restart: always
  #   build: .
  #   ports: 3000
  #   depends_on:
  #     -postgres_db
  #     -mongodb

  postgres_db:
    image: postgres
    restart: always
    container_name: postgres-db
    volumes:
      - ./database:/postgres/data
    ports:
      - 49153:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mydb

  adminer:
    image: dockette/adminer:full
    restart: always
    ports:
      - 8000:80

  mongodb:
    image: mongo
    container_name: mongodb
    environment:
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=pass12345
    volumes:
      - ./database:/mongodb/data/db
    networks:
      - mongodb_network
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass12345
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongodb
    networks:
      - mongodb_network
    ports:
      - 8081:8081

networks:
  mongodb_network:
    name: mongodb_network